### ISSUE TITLE
Code for read input from a keyboard of various data types and print them in c

### ISSUE THREAD

**Issue by krishnapatidar458** [krishnapatidar458/C-problems-Hacktoberfest2023#2]
Source file :- https://github.com/krishnapatidar458/C-problems-Hacktoberfest2023/blob/main/solutions/sol002.c

**Comment by Utkarsh212** [comment]
Please assign this to me so that I can start working on this.

**Comment by krishnapatidar458** [comment]
work and learn the basics of c programming
#Hacktoberfest2023

**Comment by RealCifer** [comment]
Hello @krishnapatidar458  hope you are doing good. I want to contribute in this issue
